# Generated by Django 4.0.3 on 2022-03-29 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen_display', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=200, null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='order',
            name='arrival_time',
            field=models.DateTimeField(null=True, verbose_name='arrival_time'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(max_length=50, null=True, verbose_name='type'),
        ),
        migrations.AddField(
            model_name='ordertodishes',
            name='quantity_done',
            field=models.IntegerField(default=0, verbose_name='quantity_done'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kitchen_display.category', verbose_name='category'),
        ),
    ]
