# Generated by Django 4.0.3 on 2022-03-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen_display', '0004_shop_local_application_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
