# Generated by Django 4.0.3 on 2022-03-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen_display', '0005_order_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('a', 'Pick up'), ('b', 'Delivery')], max_length=50, null=True, verbose_name='type'),
        ),
    ]
