# Generated by Django 4.0.3 on 2022-03-31 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen_display', '0006_alter_order_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='identifier',
            field=models.CharField(default='', max_length=50, verbose_name='remote identifier'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.CharField(default='', max_length=50, verbose_name='customer'),
        ),
    ]
