# Generated by Django 3.2.12 on 2022-04-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen_display', '0009_auto_20220415_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='switched_to_preparing_time',
            field=models.DateTimeField(null=True, verbose_name='modifier preparing time'),
        ),
    ]
