# Generated by Django 3.2.12 on 2022-04-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen_display', '0010_order_switched_to_preparing_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='switched_to_preparing_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='modifier preparing time'),
        ),
    ]
